import { Product } from './product'
export const Data : Product[] = [
    {
        id : 1,
        name : "product 1",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 2,
        name : "product 2",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 3,
        name : "product 3",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 4,
        name : "product 4",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 5,
        name : "product 5",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 6,
        name : "product 6",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 7,
        name : "product 7",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 8,
        name : "product 8",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 9,
        name : "product 9",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 10,
        name : "product 10",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 11,
        name : "product 11",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    },
    {
        id : 12,
        name : "product 12",
        price : 123,
        desc : "Mô tả sản phẩm",
        status: true,
        img : "http://placehold.it/700x400",
    }

]